# Generated by Django 4.2.30 on 2026-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('cart', 'Add to Cart'), ('purchase', 'Purchase'), ('rate', 'Rate')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_id'], name='app_userint_custome_aad0ee_idx'), models.Index(fields=['book_id'], name='app_userint_book_id_81ff14_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('similar_book_id', models.IntegerField()),
                ('score', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['book_id', '-score'], name='app_booksim_book_id_1899f0_idx')],
                'unique_together': {('book_id', 'similar_book_id')},
            },
        ),
    ]
